version: '3.8'

services:
  api:
    build: .
    container_name: blood-donation-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/blood_donation
    depends_on:
      - mongo
    volumes:
      - ./logs:/usr/src/app/logs

  mongo:
    image: mongo:7
    container_name: blood-donation-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
